const actions = {
    require: "require",
    minCharLength: "minCharLength",
    maxCharLength: "maxCharLength",
    fixCharLength: "fixCharLength",
    isNumber: "isNumber",
    isString:"isString",
    isBoolean:"isBoolean",
    isObject:"isObject",
    isNull:"isNull",
    isUndefined:"isUndefined",
    isNan:"isNan",
    minNumberLength: "minNumberLength",
    maxNumberLength: "maxNumberLength",
    fixNumberLength: "fixNumberLength",
    isPositive:"isPositive",
    isNegative:"isNegative",
    isZero:"isZero",
    min: "min",
    max: "max",
    email: "email",
    mobile: "mobile",
    date: "date",
    url: "url",
    regex: "regex",
    custom: "custom",
    guid: "guid",
};

export default actions